[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --ignore=tests/test_scraper.py --ignore=tests/test_pipeline.py --ignore=tests/application/test_probility_engine.py
