"""
Universal Market Importer & Valuator for BAgent
================================================
Imports full market catalogs exported from bookmakers (SNAI, Sisal, Bet365, Planetwin)
either via:
1. JSON export file (generated by BAgent One-Click Bookmarklet)
2. Raw clipboard / pasted palinsesto text
3. Direct API feeds

Normalizes every market (1X2, Totals, Player Props, Uno o l'Altro, Chance Mix)
and evaluates mathematical edge (+EV) against fair model prices.
"""

import json
import re
from typing import Dict, Any, List, Optional
from pathlib import Path


class UniversalMarketImporter:
    """Ingests and standardizes full market catalogs for deep valuation."""

    def __init__(self, markets_catalog: Optional[Dict[str, Any]] = None):
        self.catalog = markets_catalog or {}

    @classmethod
    def from_json_file(cls, filepath: str) -> "UniversalMarketImporter":
        """Loads markets from a JSON file exported by the BAgent browser tool."""
        p = Path(filepath)
        if not p.exists():
            raise FileNotFoundError(f"Markets file not found: {filepath}")
        with open(p, "r", encoding="utf-8") as f:
            data = json.load(f)
        return cls(data)

    @classmethod
    def from_raw_text(cls, text: str, match_name: str = "Match") -> "UniversalMarketImporter":
        """
        Parses raw copied text from SNAI / Sisal web palinsesto.
        Robustly extracts 1X2, Over/Under, Player Props, Uno o l'Altro, etc.
        """
        catalog = {
            "match": match_name,
            "markets_count": 0,
            "main_markets": {},
            "player_props": {},
            "uno_o_altro": {},
            "raw_markets": []
        }

        # 1X2 extraction
        m_1x2 = re.search(r"Esito Finale 1x2.*?1\s+X\s+2.*?([\d\.]+)\s+([\d\.]+)\s+([\d\.]+)", text, re.DOTALL)
        if m_1x2:
            catalog["main_markets"]["1X2"] = {
                "1": float(m_1x2.group(1)),
                "X": float(m_1x2.group(2)),
                "2": float(m_1x2.group(3))
            }

        # Doppia Chance
        m_dc = re.search(r"Doppia Chance.*?1X\s+X2\s+12.*?([\d\.]+)\s+([\d\.]+)\s+([\d\.]+)", text, re.DOTALL)
        if m_dc:
            catalog["main_markets"]["Doppia Chance"] = {
                "1X": float(m_dc.group(1)),
                "X2": float(m_dc.group(2)),
                "12": float(m_dc.group(3))
            }

        # Under / Over 2.5
        m_uo = re.search(r"Under/Over.*?U\s+O.*?2\.5\s+([\d\.]+)\s+([\d\.]+)", text, re.DOTALL)
        if m_uo:
            catalog["main_markets"]["Under/Over 2.5"] = {
                "Under": float(m_uo.group(1)),
                "Over": float(m_uo.group(2))
            }

        # Goal / NoGoal
        m_gg = re.search(r"Goal/NoGoal.*?GG\s+NG.*?([\d\.]+)\s+([\d\.]+)", text, re.DOTALL)
        if m_gg:
            catalog["main_markets"]["Goal/NoGoal"] = {
                "GG": float(m_gg.group(1)),
                "NG": float(m_gg.group(2))
            }

        # Uno o l'altro Cartellino
        cards_pattern = re.findall(
            r"([A-Z\s\.]+\s+O\s+[A-Z\s\.]+\s+CARTELLINO[^\n]*)\nMin - max[^\n]*\nSI\n([\d\.]+)",
            text
        )
        for pair_name, odds in cards_pattern:
            clean_name = re.sub(r"\s+", " ", pair_name.strip())
            catalog["uno_o_altro"][clean_name] = float(odds)

        # Uno o l'altro Primo Marcatore
        scorer_pattern = re.findall(
            r"(PRIMO MARCATORE\s+[A-Z\s\.]+\s+O\s+[A-Z\s\.]+[^\n]*)\nMin - max[^\n]*\nSI\n([\d\.]+)",
            text
        )
        for pair_name, odds in scorer_pattern:
            clean_name = re.sub(r"\s+", " ", pair_name.strip())
            catalog["uno_o_altro"][clean_name] = float(odds)

        # Player props table (Marcatori, Tiri in porta, Cartellini)
        # Supports both markdown links "[ItaliaESPOSITO P.]" and raw DOM text "Italia\nESPOSITO P."
        player_blocks = re.findall(
            r"\[(?:Italia|Turchia|Ospite|Casa)([^\]]+)\]\s*\n([\d\.\s\n]+)",
            text
        )
        if not player_blocks:
            player_blocks = re.findall(
                r"(?:Italia|Turchia|Ospite|Casa)\s*\n\s*([A-Z\s\.]+)\s*\n\s*([\d\.]+(?:\s*\n\s*[\d\.]+){3,})",
                text
            )

        for player_name, odds_block in player_blocks:
            clean_p = player_name.strip()
            numbers = [float(n) for n in re.findall(r"\b\d+\.\d+\b", odds_block)]
            if len(numbers) >= 2:
                catalog["player_props"][clean_p] = {
                    "raw_odds": numbers,
                    "marcatore": numbers[0] if len(numbers) > 0 else None,
                    "marcatore_piu": numbers[1] if len(numbers) > 1 else None,
                    "quasi_marcatore": numbers[2] if len(numbers) > 2 else None,
                    "cartellino": numbers[3] if len(numbers) > 3 else None,
                    "quasi_cartellino": numbers[4] if len(numbers) > 4 else None,
                    "primo_marcatore": numbers[5] if len(numbers) > 5 else None,
                    "almeno_2_gol": numbers[6] if len(numbers) > 6 else None,
                    "assist": numbers[7] if len(numbers) > 7 else None,
                }

        catalog["markets_count"] = (
            len(catalog["main_markets"]) +
            len(catalog["player_props"]) * 7 +
            len(catalog["uno_o_altro"])
        )

        return cls(catalog)

    def summary(self) -> Dict[str, Any]:
        """Returns statistical overview of ingested catalog."""
        return {
            "match": self.catalog.get("match", "Unknown"),
            "main_markets": list(self.catalog.get("main_markets", {}).keys()),
            "players_tracked": len(self.catalog.get("player_props", {})),
            "uno_o_altro_pairs": len(self.catalog.get("uno_o_altro", {})),
            "total_estimated_markets": self.catalog.get("markets_count", 0)
        }


# JavaScript code for the Bookmarklet
BOOKMARKLET_JS = """javascript:(function(){
    var matchTitle = document.title || 'Match';
    console.log('[BAgent] Inizio estrazione mercati per:', matchTitle);
    
    // 1. Clicca sul tab TUTTE se presente
    var tabs = document.querySelectorAll('button, a, div[role="tab"]');
    tabs.forEach(function(t){
        if(t.innerText && t.innerText.trim().toUpperCase() === 'TUTTE'){
            t.click();
            console.log('[BAgent] Cliccato tab TUTTE');
        }
    });

    // 2. Apri tutti gli accordéon chiusi
    setTimeout(function(){
        var accordions = document.querySelectorAll('[aria-expanded="false"], .accordion-header:not(.active)');
        accordions.forEach(function(a){ a.click(); });
        
        // 3. Estrai tutto il testo strutturato
        setTimeout(function(){
            var fullText = document.body.innerText;
            
            // Crea un link di download per il file .txt / .json
            var blob = new Blob([fullText], {type: 'text/plain;charset=utf-8'});
            var url = URL.createObjectURL(blob);
            var a = document.createElement('a');
            a.href = url;
            a.download = 'bagent_' + matchTitle.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase() + '_full_markets.txt';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            
            alert('✅ BAgent: Tutti i mercati scaricati con successo!');
        }, 800);
    }, 500);
})();"""
